spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true  
      keyvault:
        secret:
          property-source-enabled: true
          endpoint: https://<your-keyvault-name>.vault.azure.net/
